---
# File: acl.yml - ACL tasks for Consul

- block:
  - name: Generate ACL master token
    command: "echo {{ ansible_date_time.iso8601_micro | to_uuid }}"
    register: consul_acl_master_token_keygen
    run_once: true
  - name: Save ACL master token
    set_fact:
      consul_acl_master_token: "{{ consul_acl_master_token_keygen.stdout }}"
  when:
    - consul_acl_master_token is not defined
    - not bootstrap_state.stat.exists | bool

- name: Display ACL Master Token
  debug:
    msg: "{{ consul_acl_master_token }}"
  run_once: True
  when: consul_acl_master_token_display | bool

- block:
  - name: Generate ACL replication token
    command: "echo {{ ansible_date_time.iso8601_micro | to_uuid }}"
    register: consul_acl_replication_token_keygen
    run_once: true
  - name: Save ACL replication token
    set_fact:
      consul_acl_replication_token: "{{ consul_acl_replication_token_keygen.stdout }}"
  when:
    - (consul_acl_replication_token is not defined or consul_acl_replication_token == '')
    - not bootstrap_state.stat.exists | bool

- name: Create ACL policy configuration
  template:
    src: configd_50acl_policy.hcl.j2
    dest: "{{ consul_configd_path }}/50acl_policy.hcl"
    owner: "{{ consul_user }}"
    group: "{{ consul_group}}"
  notify:
    - restart consul
  when: consul_acl_policy | bool

