---
# File: client.yml - Ansible dependencies for Consul

# Apt cache should be updated here - do not remove `update_cache`

- name: Install additional Python dependencies for Ansible
  apt:
    name: "{{ item }}"
    state: installed
    update_cache: yes
  with_items:
    - python-pip
    - python-setuptools

- name: Install Consul Python package
  pip: executable=pip name=python-consul
