---
# File: main.yml - Handlers for Consul

- name: restart consul
  include: restart_consul.yml

- name: start consul
  include: start_consul.yml

- name: restart dnsmasq
  service:
    name: dnsmasq
    state: restarted
